spring:
  application:
    name: demo-eureka
  profiles:
    active: dev

server:
  port: 1111

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://10.26.193.156:${server.port}/eureka/
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 3000
    response-cache-auto-expiration-in-seconds: 180

